name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: AutomatedEmpires/.github/.github/workflows/reusable-release.yml@7f03a9b7a8304353a04addd5227f6eea87fe7769
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
